# Generated by Django 4.2.23 on 2025-10-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='comuna_text',
        ),
    ]
