# Generated by Django 4.2.23 on 2025-10-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_comuna_comuna_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocion', to='core.producto')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='core.promocion')),
            ],
            options={
                'db_table': 'promocion_producto',
            },
        ),
    ]
