# Generated by Django 4.2.23 on 2025-10-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_promocionproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('percent', 'Porcentaje'), ('fixed', 'Monto fijo')], default='percent', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_expiracion', models.DateTimeField()),
                ('uso_maximo', models.PositiveIntegerField(default=1)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
